### ISSUE TITLE
Constants are wrong

### ISSUE THREAD

**Issue by DerBensch** [HTD/FastBezier#1]
You got:
protected static double Sqrt3 = Math.Sqrt(3);
protected static double Div18Sqrt3 = 18 / Sqrt3;
protected static double OneThird = 1 / 3;
protected static double Sqrt3Div36 = Sqrt3 / 36;

You should add a .0 after the numbers. OneThird is always 0.0 for example.

**Comment by HTD** [comment]
Thanks, you're obviously right. My bad. I'm fixing this right now.
