### ISSUE TITLE
NaN length for horizontally aligned end points and control points.

### ISSUE THREAD

**Issue by rraallvv** [HTD/FastBezier#2]
I'm getting NaN for this values:

    var test = new V3D[] {
        new V3D(0, 0, 0),
        new V3D(10, 0, 0),
        new V3D(-10, 0, 0),
        new V3D(20, 0, 0)
    };

**Comment by ajihyf** [comment]
https://github.com/HTD/FastBezier/blob/master/Program.cs#L83
This line is giving NaN for colinear quadratic beziers. Maybe there should be a zero test to handle it.

**Comment by HTD** [comment]
Fixed. Passing edge case test added.
